export const LOAD_PRODUCT_DETAIL = 'LOAD_PRODUCT_DETAIL';
export const LOAD_PRODUCT_DETAIL_PENDING = 'LOAD_PRODUCT_DETAIL_PENDING';
export const LOAD_PRODUCT_DETAIL_FULFILLED = 'LOAD_PRODUCT_DETAIL_FULFILLED';
export const LOAD_PRODUCT_DETAIL_REJECTED = 'LOAD_PRODUCT_DETAIL_REJECTED';
export const LOAD_PRODUCT_DESCRIPTION = 'LOAD_PRODUCT_DESCRIPTION';
export const LOAD_PRODUCT_DESCRIPTION_PENDING = 'LOAD_PRODUCT_DESCRIPTION_PENDING';
export const LOAD_PRODUCT_DESCRIPTION_FULFILLED = 'LOAD_PRODUCT_DESCRIPTION_FULFILLED';
export const LOAD_PRODUCT_DESCRIPTION_REJECTED = 'LOAD_PRODUCT_DESCRIPTION_REJECTED';
