export const LOAD_RESULTS = 'LOAD_RESULTS';
export const LOAD_RESULTS_PENDING = 'LOAD_RESULTS_PENDING';
export const LOAD_RESULTS_FULFILLED = 'LOAD_RESULTS_FULFILLED';
export const LOAD_RESULTS_REJECTED = 'LOAD_RESULTS_REJECTED';
