export const result = {
  site_id: 'MLA',
  query: 'bicicletas',
  paging: { total: 24510, offset: 0, limit: 50, primary_results: 1000 },
  results: [{
    id: 'MLA722826078',
    site_id: 'MLA',
    title: 'Bicicleta Mountain Topmega Envoy R26 21v Shimano Armado+kit',
    seller: { id: 317973780, power_seller_status: 'platinum', car_dealer: false, real_estate_agency: false, tags: [] },
    price: 11876,
    currency_id: 'ARS',
    available_quantity: 50,
    sold_quantity: 250,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_special',
    stop_time: '2038-07-12T00:44:11.000Z',
    condition: 'new',
    permalink: 'https://articulo.mercadolibre.com.ar/MLA-722826078-bicicleta-mountain-topmega-envoy-r26-21v-shimano-armadokit-_JM',
    thumbnail: 'http://mla-s1-p.mlstatic.com/927936-MLA28764227105_112018-I.jpg',
    accepts_mercadopago: true,
    installments: { quantity: 12, amount: 1620.78, rate: 63.77, currency_id: 'ARS' },
    address: { state_id: 'AR-C', state_name: 'Capital Federal', city_id: 'TUxBQk1BVDMwMDJa', city_name: 'Mataderos' },
    shipping: { free_shipping: true, mode: 'me2', tags: ['self_service_in', 'mandatory_free_shipping'], logistic_type: 'cross_docking', store_pick_up: false },
    seller_address: {
      id: '', comment: '', address_line: '', zip_code: '', country: { id: 'AR', name: 'Argentina' }, state: { id: 'AR-C', name: 'Capital Federal' }, city: { id: 'TUxBQk1BVDMwMDJa', name: 'Mataderos' }, latitude: '', longitude: '',
    },
    attributes: [{
      value_struct: null, attribute_group_id: 'OTHERS', attribute_group_name: 'Otros', source: 4060709329251625, id: 'BRAND', name: 'Marca', value_id: '449706', value_name: 'Top Mega',
    }, {
      value_name: 'Nuevo', value_struct: null, attribute_group_id: 'OTHERS', attribute_group_name: 'Otros', source: 1138849081739375, id: 'ITEM_CONDITION', name: 'Condición del ítem', value_id: '2230284',
    }, {
      attribute_group_name: 'Otros', source: 4060709329251625, id: 'MODEL', name: 'Modelo', value_id: '123195', value_name: 'Envoy', value_struct: null, attribute_group_id: 'OTHERS',
    }],
    original_price: 17759,
    category_id: 'MLA65817',
    official_store_id: 1429,
    catalog_product_id: null,
    reviews: { rating_average: 4.2, total: 21 },
    tags: ['brand_verified', 'good_quality_picture', 'good_quality_thumbnail', 'immediate_payment', 'cart_eligible'],
  }, {
    id: 'MLA741137679',
    site_id: 'MLA',
    title: 'Bicicleta Mountain Topmega Envoy R26 21v Shimano +armado ',
    seller: { id: 317973780, power_seller_status: 'platinum', car_dealer: false, real_estate_agency: false, tags: [] },
    price: 12790,
    currency_id: 'ARS',
    available_quantity: 50,
    sold_quantity: 100,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_pro',
    stop_time: '2038-07-30T14:59:57.000Z',
    condition: 'new',
    permalink: 'https://articulo.mercadolibre.com.ar/MLA-741137679-bicicleta-mountain-topmega-envoy-r26-21v-shimano-armado-_JM',
    thumbnail: 'http://mla-s2-p.mlstatic.com/818636-MLA27902505415_082018-I.jpg',
    accepts_mercadopago: true,
    installments: { quantity: 6, amount: 2131.67, rate: 0, currency_id: 'ARS' },
    address: { state_id: 'AR-C', state_name: 'Capital Federal', city_id: 'TUxBQk1BVDMwMDJa', city_name: 'Mataderos' },
    shipping: { free_shipping: true, mode: 'me2', tags: ['self_service_in', 'mandatory_free_shipping'], logistic_type: 'cross_docking', store_pick_up: false },
    seller_address: {
      id: '', comment: '', address_line: '', zip_code: '', country: { id: 'AR', name: 'Argentina' }, state: { id: 'AR-C', name: 'Capital Federal' }, city: { id: 'TUxBQk1BVDMwMDJa', name: 'Mataderos' }, latitude: '', longitude: '',
    },
    attributes: [{
      value_struct: null, attribute_group_id: 'OTHERS', attribute_group_name: 'Otros', source: 4060709329251625, id: 'BRAND', name: 'Marca', value_id: '449706', value_name: 'Top Mega',
    }, {
      attribute_group_id: 'OTHERS', attribute_group_name: 'Otros', source: 1, id: 'ITEM_CONDITION', name: 'Condición del ítem', value_id: '2230284', value_name: 'Nuevo', value_struct: null,
    }, {
      attribute_group_id: 'OTHERS', attribute_group_name: 'Otros', source: 4060709329251625, id: 'MODEL', name: 'Modelo', value_id: '123195', value_name: 'Envoy', value_struct: null,
    }],
    differential_pricing: { id: 33600181 },
    original_price: 19535,
    category_id: 'MLA65817',
    official_store_id: 1429,
    catalog_product_id: 'MLA12861104',
    reviews: { rating_average: 4.6, total: 189 },
    tags: ['good_quality_thumbnail', 'brand_verified', 'good_quality_picture', 'immediate_payment', 'cart_eligible'],
  }, {
    id: 'MLA601795056',
    site_id: 'MLA',
    title: 'Bicicleta Mtb Bike 26 Doble Susp 21 Vel + Linga Elegí Color!',
    seller: { id: 3255473, power_seller_status: 'platinum', car_dealer: false, real_estate_agency: false, tags: [] },
    price: 6498,
    currency_id: 'ARS',
    available_quantity: 50,
    sold_quantity: 500,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_special',
    stop_time: '2036-03-31T17:42:38.000Z',
    condition: 'new',
    permalink: 'https://articulo.mercadolibre.com.ar/MLA-601795056-bicicleta-mtb-bike-26-doble-susp-21-vel-linga-elegi-color-_JM',
    thumbnail: 'http://mla-s1-p.mlstatic.com/684597-MLA29020871766_122018-I.jpg',
    accepts_mercadopago: true,
    installments: { quantity: 12, amount: 886.81, rate: 63.77, currency_id: 'ARS' },
    address: { state_id: 'AR-C', state_name: 'Capital Federal', city_id: '', city_name: 'Buenos Aires' },
    shipping: { free_shipping: true, mode: 'me2', tags: ['self_service_out', 'mandatory_free_shipping'], logistic_type: 'cross_docking', store_pick_up: false },
    seller_address: {
      id: '', comment: '', address_line: '', zip_code: '', country: { id: 'AR', name: 'Argentina' }, state: { id: 'AR-C', name: 'Capital Federal' }, city: { id: '', name: 'Buenos Aires' }, latitude: '', longitude: '',
    },
    attributes: [{
      source: 1572, id: 'BRAND', name: 'Marca', value_id: null, value_name: 'Forest', value_struct: null, attribute_group_id: 'OTHERS', attribute_group_name: 'Otros',
    }, {
      value_name: 'Nuevo', value_struct: null, attribute_group_id: 'OTHERS', attribute_group_name: 'Otros', source: 1, id: 'ITEM_CONDITION', name: 'Condición del ítem', value_id: '2230284',
    }, {
      name: 'Modelo', value_id: null, value_name: '10284', value_struct: null, attribute_group_id: 'OTHERS', attribute_group_name: 'Otros', source: 1572, id: 'MODEL',
    }],
    original_price: 8980,
    category_id: 'MLA65817',
    official_store_id: null,
    catalog_product_id: null,
    reviews: { rating_average: 4.4, total: 210 },
    tags: ['good_quality_picture', 'good_quality_thumbnail', 'dragged_bids_and_visits', 'immediate_payment', 'cart_eligible'],
  }, {
    id: 'MLA739944416',
    site_id: 'MLA',
    title: 'Bicicleta Slp 10 Pro R29 Shimano 21v F/ Disco Susp + Linga',
    seller: { id: 70513647, power_seller_status: 'platinum', car_dealer: false, real_estate_agency: false, tags: [] },
    price: 10663,
    currency_id: 'ARS',
    available_quantity: 500,
    sold_quantity: 500,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_special',
    stop_time: '2038-07-24T04:00:00.000Z',
    condition: 'new',
    permalink: 'https://articulo.mercadolibre.com.ar/MLA-739944416-bicicleta-slp-10-pro-r29-shimano-21v-f-disco-susp-linga-_JM',
    thumbnail: 'http://mla-s1-p.mlstatic.com/740685-MLA27860421767_072018-I.jpg',
    accepts_mercadopago: true,
    installments: { quantity: 12, amount: 1455.23, rate: 63.77, currency_id: 'ARS' },
    address: { state_id: 'AR-B', state_name: 'Buenos Aires', city_id: '', city_name: 'Lomas de Zamora' },
    shipping: { free_shipping: true, mode: 'me2', tags: ['self_service_in', 'mandatory_free_shipping'], logistic_type: 'cross_docking', store_pick_up: false },
    seller_address: {
      id: '', comment: '', address_line: '', zip_code: '', country: { id: 'AR', name: 'Argentina' }, state: { id: 'AR-B', name: 'Buenos Aires' }, city: { id: '', name: 'Lomas de Zamora' }, latitude: '', longitude: '',
    },
    attributes: [{
      value_struct: null, attribute_group_id: 'OTHERS', attribute_group_name: 'Otros', source: 6795511568268166, id: 'BRAND', name: 'Marca', value_id: '5411077', value_name: 'SLP',
    }, {
      name: 'Condición del ítem', value_id: '2230284', value_name: 'Nuevo', value_struct: null, attribute_group_id: 'OTHERS', attribute_group_name: 'Otros', source: 1572, id: 'ITEM_CONDITION',
    }, {
      attribute_group_id: 'OTHERS', attribute_group_name: 'Otros', source: 1572, id: 'MODEL', name: 'Modelo', value_id: null, value_name: '10 Pro', value_struct: null,
    }],
    original_price: null,
    category_id: 'MLA404269',
    official_store_id: null,
    catalog_product_id: 'MLA12861090',
    reviews: { rating_average: 4.5, total: 237 },
    tags: ['good_quality_picture', 'good_quality_thumbnail', 'brand_verified', 'immediate_payment', 'cart_eligible'],
  }],
  secondary_results: [],
  related_results: [],
  sort: { id: 'relevance', name: 'Más relevantes' },
  available_sorts: [{ id: 'price_asc', name: 'Menor precio' }, { id: 'price_desc', name: 'Mayor precio' }],
  filters: [{ id: 'category', name: 'Categorías', type: 'text', values: [{ id: 'MLA6143', name: 'Bicicletas', path_from_root: [{ id: 'MLA1276', name: 'Deportes y Fitness' }, { id: 'MLA1292', name: 'Bicicletas y Ciclismo' }, { id: 'MLA6143', name: 'Bicicletas' }] }] }, { id: '9996143-AMLA_6143_1', name: 'Edad', type: 'text', values: [{ id: '9996143-AMLA_6143_1-MMLA31441', name: 'Adultos' }] }],
  available_filters: [{ id: 'official_store', name: 'Tiendas oficiales', type: 'text', values: [{ id: 'all', name: 'Todas las tiendas oficiales', results: 351 }, { id: '1429', name: 'TOPMEGA', results: 40 }, { id: '1213', name: 'Hendel Hogar', results: 1 }] }, { id: '9996143-AMLA_6143_2', name: 'Tipo', type: 'text', values: [{ id: '9996143-AMLA_6143_2-MMLA31445', name: 'Mountain Bike', results: 12008 }, { id: '9996143-AMLA_6143_2-MMLA83191', name: 'De Paseo', results: 3646 }, { id: '9996143-AMLA_6143_2-MMLA83190', name: 'De Ruta', results: 2365 }, { id: '9996143-AMLA_6143_2-MMLA31447', name: 'Playeras', results: 1940 }, { id: '9996143-AMLA_6143_2-MMLA51325', name: 'Plegables', results: 1454 }, { id: '9996143-AMLA_6143_2-MMLA31444', name: 'BMX', results: 801 }, { id: '9996143-AMLA_6143_2-MMLA51324', name: 'Fixie', results: 616 }, { id: '9996143-AMLA_6143_2-MMLA31446', name: 'Otras Bicicletas', results: 1680 }] }, { id: '9996143-AMLA_6143_3', name: 'Rodado', type: 'text', values: [{ id: '9996143-AMLA_6143_3-MMLA31455', name: 'Rodado 26', results: 8970 }, { id: '9996143-AMLA_6143_3-MMLA83192', name: 'Rodado 29', results: 5596 }, { id: '9996143-AMLA_6143_3-MMLA31456', name: 'Rodado 28', results: 3963 }, { id: '9996143-AMLA_6143_3-MMLA31453', name: 'Rodado 20', results: 2145 }, { id: '9996143-AMLA_6143_3-MMLA51374', name: 'Rodado 27.5', results: 1391 }, { id: '9996143-AMLA_6143_3-MMLA31454', name: 'Rodado 24', results: 785 }, { id: '9996143-AMLA_6143_3-MMLA31449', name: 'Otros Rodados', results: 1660 }] }, { id: 'discount', name: 'Descuentos', type: 'range', values: [{ id: '10-100', name: 'Desde 10% off', results: 631 }, { id: '20-100', name: 'Desde 20% off', results: 586 }, { id: '30-100', name: 'Desde 30% off', results: 90 }, { id: '40-100', name: 'Desde 40% off', results: 7 }] }, { id: 'state', name: 'Ubicación', type: 'text', values: [{ id: 'TUxBUENBUGw3M2E1', name: 'Capital Federal', results: 8092 }, { id: 'TUxBUEdSQXJlMDNm', name: 'Bs.As. G.B.A. Sur', results: 3294 }, { id: 'TUxBUEdSQWU4ZDkz', name: 'Bs.As. G.B.A. Norte', results: 3199 }, { id: 'TUxBUEdSQWVmNTVm', name: 'Bs.As. G.B.A. Oeste', results: 2454 }, { id: 'TUxBUENPUmFkZGIw', name: 'Córdoba', results: 2186 }, { id: 'TUxBUFNBTmU5Nzk2', name: 'Santa Fe', results: 1310 }, { id: 'TUxBUFpPTmFpbnRl', name: 'Buenos Aires Interior', results: 1071 }, { id: 'TUxBUE1FTmE5OWQ4', name: 'Mendoza', results: 550 }, { id: 'TUxBUFRVQ244NmM3', name: 'Tucumán', results: 430 }, { id: 'TUxBUEVOVHMzNTdm', name: 'Entre Ríos', results: 396 }, { id: 'TUxBUENPU2ExMmFkMw', name: 'Bs.As. Costa Atlántica', results: 290 }, { id: 'TUxBUE5FVW4xMzMzNQ', name: 'Neuquén', results: 255 }, { id: 'TUxBUFNBTGFjMTJi', name: 'Salta', results: 195 }, { id: 'TUxBUFNBTm5lYjU4', name: 'San Juan', results: 195 }, { id: 'TUxBUFLNT29iZmZm', name: 'Río Negro', results: 180 }, { id: 'TUxBUFNBTnM0ZTcz', name: 'San Luis', results: 170 }, { id: 'TUxBUENIQW8xMTNhOA', name: 'Chaco', results: 155 }, { id: 'TUxBUENIVXQxNDM1MQ', name: 'Chubut', results: 155 }, { id: 'TUxBUExBWmE1OWMy', name: 'La Pampa', results: 145 }, { id: 'TUxBUEpVSnk3YmUz', name: 'Jujuy', results: 130 }, { id: 'TUxBUExBWmEyNzY0', name: 'La Rioja', results: 110 }, { id: 'TUxBUENBVGFiY2Fm', name: 'Catamarca', results: 85 }, { id: 'TUxBUENPUnM5MjI0', name: 'Corrientes', results: 85 }, { id: 'TUxBUFNBTm9lOTlk', name: 'Santiago del Estero', results: 85 }, { id: 'TUxBUE1JU3MzNjIx', name: 'Misiones', results: 75 }, { id: 'TUxBUEZPUmE1OTk5', name: 'Formosa', results: 50 }, { id: 'TUxBUFNBTno3ZmY5', name: 'Santa Cruz', results: 30 }, { id: 'TUxBUFRJRVoxM2M5YQ', name: 'Tierra del Fuego', results: 15 }] }, { id: 'price', name: 'Precio', type: 'range', values: [{ id: '*-8000.0', name: 'Hasta $ 8.000', results: 7790 }, { id: '8000.0-20000.0', name: '$8.000 a $20.000', results: 8424 }, { id: '20000.0-*', name: 'Más de $20.000', results: 8296 }] }, { id: 'accepts_mercadopago', name: 'Filtro por MercadoPago', type: 'boolean', values: [{ id: 'yes', name: 'Con MercadoPago', results: 24510 }] }, { id: 'installments', name: 'Pago', type: 'text', values: [{ id: 'yes', name: 'En cuotas', results: 24380 }, { id: 'no_interest', name: 'Sin interés', results: 2947 }] }, { id: 'condition', name: 'Condición', type: 'text', values: [{ id: 'new', name: 'Nuevo', results: 11930 }, { id: 'used', name: 'Usado', results: 12255 }] }, { id: 'shipping', name: 'Tipo de entrega', type: 'text', values: [{ id: 'mercadoenvios', name: 'Con envío', results: 2300 }] }, { id: 'power_seller', name: 'Filtro por calidad de vendedores', type: 'boolean', values: [{ id: 'yes', name: 'Mejores vendedores', results: 5690 }] }, { id: 'buying_mode', name: 'Filtro por tipo de venta', type: 'text', values: [{ id: 'buy_it_now', name: 'Compra inmediata', results: 24510 }] }, { id: 'since', name: 'Filtro por fecha de comienzo', type: 'text', values: [{ id: 'today', name: 'Publicados hoy', results: 255 }] }, { id: 'until', name: 'Filtro por fecha de finalización', type: 'text', values: [{ id: 'today', name: 'Finalizan hoy', results: 135 }] }, { id: 'has_video', name: 'Filtro por publicaciones con video', type: 'boolean', values: [{ id: 'yes', name: 'Publicaciones con video', results: 1087 }] }, { id: 'has_pictures', name: 'Filtro por publicaciones con imágenes', type: 'boolean', values: [{ id: 'yes', name: 'Con fotos', results: 24450 }] }, { id: 'product', name: 'Producto', type: 'text', values: [{ id: 'MLA12943084', name: 'Venzo Eolo Adultos', results: 143 }, { id: 'MLA12861116', name: 'Venzo Skyline Adultos', results: 139 }, { id: 'MLA13111448', name: 'Philco Escape Adultos Unisex', results: 116 }, { id: 'MLA12861117', name: 'Venzo Skyline Adultos - 29', results: 104 }, { id: 'MLA12943050', name: 'Top Mega Neptune Adultos', results: 98 }, { id: 'MLA12861088', name: 'SLP 100 Pro Adultos', results: 93 }, { id: 'MLA12861095', name: 'SLP 50 Pro Adultos', results: 79 }, { id: 'MLA12943076', name: 'Vairo XR 4.0 Adultos', results: 76 }, { id: 'MLA12972498', name: 'Philco Sicilia Adultos Femenino', results: 66 }, { id: 'MLA12861083', name: 'Philco Vertical Adultos', results: 63 }, { id: 'MLA12861114', name: 'Top Mega Thor Adultos', results: 61 }, { id: 'MLA12861103', name: 'Top Mega Envoy Adultos', results: 54 }, { id: 'MLA12943085', name: 'Venzo Eolo Adultos - 29', results: 53 }, { id: 'MLA12972500', name: 'Philco Toscana Adultos Masculino', results: 51 }, { id: 'MLA12861084', name: 'Philco Vertical Adultos - 26', results: 48 }, { id: 'MLA12943051', name: 'Top Mega Neptune Adultos - 26', results: 48 }, { id: 'MLA12861096', name: 'SLP 50 Pro Adultos - 29', results: 44 }, { id: 'MLA12861104', name: 'Top Mega Envoy Adultos - 26', results: 34 }, { id: 'MLA12861111', name: 'Top Mega Rowen Adultos', results: 33 }, { id: 'MLA12861090', name: 'SLP 100 Pro Adultos - 29', results: 32 }, { id: 'MLA12861110', name: 'Top Mega Mustang Adultos - 29', results: 27 }, { id: 'MLA12972499', name: 'Philco Sicilia Adultos Femenino - 28', results: 26 }, { id: 'MLA12861094', name: 'SLP 300 Pro Adultos - 29', results: 16 }, { id: 'MLA12861108', name: 'Top Mega Folding Adultos - 20', results: 12 }, { id: 'MLA12861112', name: 'Top Mega Rowen Adultos - 26', results: 12 }, { id: 'MLA12861115', name: 'Top Mega Thor Adultos - 29', results: 11 }, { id: 'MLA12943016', name: 'SLP 10 Pro Adultos - 29', results: 11 }] }, { id: 'shipping_cost', name: 'Costo de envío', type: 'text', values: [{ id: 'free', name: 'Gratis', results: 4402 }] }],
};
